"""Conformance against an external reference implementation.

Every other test in this suite checks that the identicon behaves the way we
said it would. These check that the way we said it would behave is somebody
else's rule, which is a different claim and the one that was missing.

`identicon/vectors.json` was produced by running
[stewartlord/identicon.js](https://github.com/stewartlord/identicon.js),
unmodified, under node. It is not generated by this project's code. An earlier
attempt at conformance was abandoned on the grounds that pinning vectors for a
derivation we invented "proved only that the code agrees with itself"; these
vectors exist so that objection no longer applies.

The library is not vendored. `identicon/reference/README.md` says how to fetch
it and regenerate the file.
"""

import json
import shutil
import subprocess
import unittest

import support

identicon = support.load_script(support.IDENTICON, "identicon_conformance")

VECTORS = json.loads((support.REPO_ROOT / "identicon" / "vectors.json").read_text())


class TestVectorsAreUsable(unittest.TestCase):

    def test_the_vectors_exist_and_cover_the_awkward_cases(self):
        """A conformance file that only holds happy paths conforms to nothing
        interesting. The empty key and the single character are the two the
        grid rule is most likely to get wrong at the edges."""
        self.assertGreaterEqual(len(VECTORS), 10)
        keys = {vector["key"] for vector in VECTORS}
        self.assertIn("", keys)
        self.assertIn("a", keys)
        self.assertTrue(any(key.startswith("gitlab.com/") for key in keys),
                        "a non-GitHub host must be covered; the host is part of the key")
        self.assertTrue(any(key.startswith("/") for key in keys),
                        "a path-shaped fallback key must be covered")


class TestGridConformance(unittest.TestCase):

    def test_every_vector_grid_matches(self):
        for vector in VECTORS:
            with self.subTest(key=vector["key"]):
                grid = identicon.identicon_grid(vector["key"])
                rendered = ["".join("1" if cell else "0" for cell in row)
                            for row in grid]
                self.assertEqual(vector["grid"], rendered)

    def test_the_digest_matches_the_reference(self):
        """If the digests diverge nothing downstream can agree, and the failure
        would show up as a wrong picture rather than a wrong hash."""
        for vector in VECTORS:
            with self.subTest(key=vector["key"]):
                self.assertEqual(vector["md5"], identicon._digest(vector["key"]))


class TestColourConformance(unittest.TestCase):

    def test_every_vector_colour_matches(self):
        for vector in VECTORS:
            with self.subTest(key=vector["key"]):
                colour = identicon.hex_colour(identicon.identicon_colour(vector["key"]))
                self.assertEqual(vector["foreground"], colour)

    def test_the_defaults_are_the_reference_defaults(self):
        """The reference fixes saturation and lightness. Deriving them from the
        digest is what dgraham/identicon does, and taking one rule from each
        would be a specification neither implements."""
        self.assertEqual(0.7, identicon.SATURATION)
        self.assertEqual(0.5, identicon.LIGHTNESS)


class TestTheVectorsAreStillWhatTheReferenceProduces(unittest.TestCase):
    """Re-derive the vectors from the vendored library and compare.

    Without this, `vectors.json` is a file the repository asserts is reference
    output. With it, that assertion is checked on every run against the library
    itself -- which is the only reason the library is committed rather than
    fetched. A reference that must be downloaded is a reference that can vanish,
    and one did vanish during the week this was written.
    """

    HARNESS = support.REPO_ROOT / "identicon" / "reference" / "js-vectors.js"

    @unittest.skipUnless(shutil.which("node"), "node is not installed")
    def test_the_reference_still_produces_the_pinned_vectors(self):
        result = subprocess.run(
            ["node", str(self.HARNESS)] + [vector["key"] for vector in VECTORS],
            capture_output=True, text=True, timeout=60,
            cwd=str(self.HARNESS.parent),
        )
        self.assertEqual(0, result.returncode, result.stderr)
        self.assertEqual(VECTORS, json.loads(result.stdout))


class TestBackgroundIsADeliberateDivergence(unittest.TestCase):

    def test_the_reference_background_is_recorded_but_not_used(self):
        """The reference paints #f0f0f0 behind the grid. We render transparent,
        because the panel and the chat both sit on backgrounds we do not choose
        and cannot predict. Recorded in the vectors so the divergence stays
        visible rather than becoming folklore."""
        for vector in VECTORS:
            self.assertEqual("#f0f0f0", vector["background"])


if __name__ == "__main__":
    unittest.main()
